### PR TITLE
feat: adding highlighting support for Solidity

### PR DESCRIPTION
**Pull request by erunion**
## 🧰 What's being changed?

This adds support for highlighting the Solidity language, as requested on https://github.com/Kong/httpsnippet/issues/236.

## 🧪 Testing

* [ ] The snippet look ok? I pulled it from https://github.com/leachim6/hello-world/blob/master/s/Solidity.sol
* [ ] Tests pass?

### CODE REVIEW

**Review by domharrington — APPROVED** [review]

**Comment by michael-cohen-eth** [comment]
Hey,

Just curious to see if this change is safe to merge now and can be merged in now? Would be a huge win for our product to have solidity support for code samples

**Comment by erunion** [comment]
@michael-cohen-eth We've got a bit of a logjam with some big deploys and launches this week so I'm holding off for another day or two. This'll likely hit our release window for next week.

**Comment by michael-cohen-eth** [comment]
Is this something that will get integrated into the readme product directly soon, or is this a standalone tool for developers to use?

**Comment by erunion** [comment]
I am currently integrating it into our Markdown engine (https://github.com/readmeio/markdown/pull/391) and when that's done it'll be available to ReadMe customers. Currently aiming for this work to go out in our next deploy on Tuesday.

**Comment by erunion** [comment]
@michael-cohen-eth This is rolling out to production right now.

Screen Shot 2021-12-14 at 2 34 36 PM

**Comment by michael-cohen-eth** [comment]
Thank you! 

Just curious, will there be work done later on to give some more distinct coloring to names vs keywords in Solidity? Right now it looks like a very uniform coloring is applied. Also, there appears to be an issue with how the numbering is highlighted on Line #1

**Comment by erunion** [comment]
We're currently mapping the language to the [clike](https://github.com/codemirror/CodeMirror/tree/master/mode/clike) mode in CodeMirror so any changes would have to happen there, and we currently don't have any plans to submit improvements upstream for that.

I'm not super familiar with the language but if there's a mode available in CodeMirror that would work better for Solidity let me know and we can move our interpreter over to use that instead of `clike`.

**Comment by erunion** [comment]
Regarding the highlighting on line 1 in that screeenshot, that's a known issue atm. The version of CM we have installed at the moment is a few months and that line highlighting has since been fixed. We've been running into issues getting CM updated to the latest and currently don't have a timeline for that but it's something we're aware of.

**Pull request merged**
